import type { Metadata } from "next";
// Geistフォントのインポートは元のまま維持します
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 型定義を元の正しい状態に戻します
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* bodyタグからclassNameを削除しました。
        これにより、page.jsxで指定した背景色（bg-gray-100など）が
        正しく反映されるようになります。
      */}
      <body>
        {children}
      </body>
    </html>
  );
}

